# Generated by Django 5.0.2 on 2024-02-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_otp_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='OTP_Manager',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
