# Generated by Django 5.0.2 on 2024-03-02 11:11

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890+=&?abcdefghijklmnopqrstuvwxyz', length=30, max_length=35, prefix='', unique=True),
        ),
    ]
