# Generated by Django 5.0.2 on 2024-03-02 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddysocial', '0021_delete_bookmark'),
        ('chat', '0008_alter_chatroom_receiver_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='receiver_user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_user_profile', to='buddysocial.profile'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='sender_user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_user_profile', to='buddysocial.profile'),
        ),
    ]
