# Generated by Django 5.0.2 on 2024-03-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_chat_options_chatmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatManager',
        ),
    ]
