# Generated by Django 5.0.2 on 2024-03-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddysocial', '0015_alter_comment_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='number_of_comments',
            field=models.IntegerField(default=0),
        ),
    ]
