# Generated by Django 5.0.2 on 2024-03-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddysocial', '0016_story_number_of_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='buddysocial.profile'),
        ),
        migrations.DeleteModel(
            name='FollowUnfollowManager',
        ),
    ]
