# Generated by Django 5.0.2 on 2024-03-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddysocial', '0019_rename_story_bookmark_manager_story2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark_manager',
            old_name='story2',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='bookmark_manager',
            old_name='user2',
            new_name='user',
        ),
    ]
