# Generated by Django 5.0.2 on 2024-03-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddysocial', '0020_rename_story2_bookmark_manager_story_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
