# Generated by Django 5.0.2 on 2024-03-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddysocial', '0021_delete_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile'),
        ),
    ]
